name: CI/CD Pipeline for Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Kubernetes context
      - name: Configure Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      # Step 3: Install Helm
      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Step 4: Lint the Helm chart
      - name: Helm Lint
        run: |
          helm lint helm-charts/my-app

      # Step 5: Deploy the application
      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install my-app helm-charts/my-app --namespace default --create-namespace

